- name: Run Install from cli
  vars_files: 
    - vars/vars.yml
    
  hosts: "{{ host }}"
  gather_facts: no
  become: yes
  vars_prompt:
    - name: password1
      prompt: What is your password?
      private: no
      default: Defaultpassword

  tasks:

    - name: Run main task
      include_tasks: "main_oasys_init.yml"