- name: Install 
  vars_files: 
    - vars/vars.yml
  hosts: "{{ host }}"
  gather_facts: no
  become: yes
  tasks:

    - name: Temporarly run a docker 
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ source_image_name }}"
        entrypoint: "{{ entrypoint_cmd }}"
        detach: yes
        interactive: yes
        tty: yes
        volumes: 
          - "{{ volume_name }}:{{ container_mount_point }}"

    # - name: Some preparation before start
    #   community.docker.docker_container_exec:
    #     container: "{{ container_name }}"
    #     command: sh -c " {{ item }} "
    #   with_items: "{{ prepare_command_list }} "
        
     
        

    - name: Find required string and save it
      community.docker.docker_container_exec:  
        container: "{{ container_name }}"
        command: sh -c " {{ single_command1 }} " 
      register: out
    #  with_items: "{{ single_command1 }}"

    - name: Print stderr lines
      debug:
        msg: "{{ out }}"

        

        
