- name: Install 
  vars_files: 
    - vars/vars.yml
  hosts: "{{ host }}"
  gather_facts: no
  become: yes
  tasks:

    - name: Temporarly run a docker 
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ source_image_name }}"
        entrypoint: "{{ entrypoint_cmd }}"
        detach: yes
        interactive: yes
        tty: yes
        volumes: 
          - "{{ volume_name }}:{{ container_mount_point }}"

    - name: Some preparation before start
      community.docker.docker_container_exec:
        container: "{{ container_name }}"
      # command: "{{ shell_cmd }} {{ item }}"
     #with_items: "{{ test_list }} "
        command: "{{ shell_cmd }} {{ item }}" 
      with_items:
        - mkdir -p /root/.ethereum/geth/
        

    - name: Find required string and save it
      community.docker.docker_container_exec:  
        container: "{{ container_name }}"
        command: "{{ shell_cmd }} {{ single_command1 }}"
      register: result

    - name: Print stderr lines
      debug:
        var: result

        

        
